import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAnalysisStore } from '../store/analysisStore';
import { ScoreRing } from '../components/ui/ScoreRing';
import { AIInsightCard } from '../components/ui/AIInsightCard';

export const Report = () => {
  const { jobId } = useParams();
  const navigate = useNavigate();
  const { results, datasetName } = useAnalysisStore();

  if (!results) {
    navigate('/');
    return null;
  }

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white min-h-screen text-black p-10 font-body relative" id="report-content">
      <div className="fixed top-8 right-8 space-x-4 print:hidden">
        <button onClick={() => navigate(-1)} className="px-6 py-2 bg-gray-200 text-gray-800 rounded font-mono font-bold hover:bg-gray-300">
          Back
        </button>
        <button onClick={handlePrint} className="px-6 py-2 bg-[#f97316] text-white rounded font-mono font-bold shadow-lg hover:shadow-xl transition-shadow">
          Export PDF
        </button>
      </div>

      <div className="max-w-4xl mx-auto border border-gray-200 shadow-xl p-16 print:border-none print:shadow-none bg-white">
        <header className="border-b-4 border-[#111118] pb-6 mb-10 flex justify-between items-end">
          <div>
            <h1 className="font-display font-bold text-4xl text-[#0a0a0f] mb-2">DataForge Analysis Report</h1>
            <p className="font-mono text-gray-600">Dataset: <strong>{datasetName}</strong></p>
            <p className="font-mono text-gray-600">Job ref: {jobId}</p>
          </div>
          <div className="text-right">
            <p className="font-mono font-bold text-[#f97316]">DATE: {new Date().toLocaleDateString()}</p>
            <p className="font-mono text-sm text-gray-400">Gen-AI Enabled</p>
          </div>
        </header>

        <section className="mb-10">
          <h2 className="font-display font-semibold text-xl mb-4 bg-gray-100 p-2 border-l-4 border-[#f97316]">1. Executive Summary</h2>
          <div className="text-gray-800 leading-relaxed font-body border border-gray-200 p-6 rounded bg-gray-50 italic">
            "{results.overview.summary}" - Claude Analytics
          </div>
        </section>

        <section className="mb-10 grid grid-cols-2 gap-8">
          <div>
            <h2 className="font-display font-semibold text-xl mb-4 bg-gray-100 p-2 border-l-4 border-[#a855f7]">2. Core Metrics</h2>
            <ul className="space-y-3 font-mono text-sm border border-gray-200 p-4 rounded">
              <li className="flex justify-between border-b pb-2"><span>Rows</span> <strong>{results.overview.stats.rows.toLocaleString()}</strong></li>
              <li className="flex justify-between border-b pb-2"><span>Columns</span> <strong>{results.overview.stats.cols}</strong></li>
              <li className="flex justify-between border-b pb-2"><span>Size</span> <strong>{results.overview.stats.size}</strong></li>
              <li className="flex justify-between border-b pb-2 text-red-600"><span>CRITICAL ISSUES</span> <strong>{results.overview.issues.critical}</strong></li>
              <li className="flex justify-between text-orange-600"><span>WARNINGS</span> <strong>{results.overview.issues.warning}</strong></li>
            </ul>
          </div>
          <div className="flex flex-col items-center justify-center border border-gray-200 p-4 rounded">
            <h3 className="font-display font-bold text-gray-400 mb-2">Quality Score (DQS)</h3>
            <span className="text-6xl font-bold font-mono text-[#f97316]">{results.overview.dqs.toFixed(1)}</span>
            <span className="text-sm font-mono mt-2 text-gray-500">/ 100</span>
          </div>
        </section>

        <section className="mb-10 page-break-before">
          <h2 className="font-display font-semibold text-xl mb-4 bg-gray-100 p-2 border-l-4 border-[#f97316]">3. Dimension Breakdown</h2>
          <div className="grid grid-cols-4 gap-4 text-center">
             {Object.entries(results.overview.dimensions).map(([k, v]: [string, any]) => (
                <div key={k} className="border border-gray-200 rounded p-4">
                  <div className={`text-2xl font-bold font-mono ${v > 80 ? 'text-green-600' : 'text-red-500'}`}>{v}%</div>
                  <div className="mt-2 text-xs font-mono uppercase text-gray-600">{k}</div>
                </div>
             ))}
          </div>
        </section>

        <footer className="mt-24 pt-6 border-t font-mono text-center text-sm text-gray-400">
           Generated by DataForge Automated Analytics <br/>
           dataforge-ai.local
        </footer>
      </div>
    </div>
  );
};